### GET / 
GET http://localhost:5003

### Register a user POST / AUTH / REGISTER
POST http://localhost:5003/auth/register  
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Login a user POST / AUTH / LOGIN
POST http://localhost:5003/auth/login 
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Login a user POST / AUTH / LOGIN
POST http://localhost:5003/auth/login 
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "1"
}


###
GET http://localhost:5003/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA


### 
POST http://localhost:5003/admin/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA
{
  "name":"f1",
  "category":["Tinh cam", "Hanh dong"],
  "language":"Tieng Viet",
  "duration":"120",
  "releaseDay":"2025-08-18",
  "IMDBrating":"9.1",
  "description":"Ke ve cuoc doi cua Ngo Long",
  "directors":["Trần Quốc Thiện"],
  "writers":["Trần Quốc Thiện"],
  "actors":["Ngô Bảo Long"],
  "ageLimit":"18",
  "status":"active",
  "posterURL":"posterURL",
  "backdropURL":"posterURL"
}


### 
PUT http://localhost:5003/admin/movies/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA
{
  "name":"f1",
  "category":["Tinh cam", "Kinh di"],
  "language":"Tieng Viet",
  "duration":"120",
  "releaseDay":"2025-08-18",
  "IMDBrating":"9.1",
  "description":"Ke ve cuoc doi cua Ngo Long",
  "directors":["Trần Quốc Thiện"],
  "writers":["Trần Quốc Thiện"],
  "actors":["Ngô Bảo Long"],
  "ageLimit":"18",
  "status":"active",
  "posterURL":"posterURL",
  "backdropURL":"posterURL"
}
###
GET http://localhost:5003/admin/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA

###
DELETE http://localhost:5003/admin/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA

### 
GET http://localhost:5003/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA


###
POST http://localhost:5003/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzMzNDAsImV4cCI6MTc1NTY3Njk0MH0.8Dfs_RmGNimo5mX0hOgiQsg8yryN8g7nUnFD7GmglLE

{
  "email": "thinh@gmail.com",
  "password": "123456",
  "role": "user"
}


###
PUT http://localhost:5003/admin/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzY5NjgsImV4cCI6MTc1NTY4MDU2OH0.hNPxaZC9fawjRAWOjjj3wissFSVw6gqTeVchZSZFUo4

{
  "role": "user"
}

### 
DELETE http://localhost:5003/admin/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzMzNDAsImV4cCI6MTc1NTY3Njk0MH0.8Dfs_RmGNimo5mX0hOgiQsg8yryN8g7nUnFD7GmglLE

###
GET http://localhost:5003/user/movies
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU1Njc1MjQwLCJleHAiOjE3NTU2Nzg4NDB9.YixWgWeZwOc3-MaBRfKyglZOb9fyNivUGa5h0fN0lCw

### 
GET http://localhost:5003/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU1Njc1MjQwLCJleHAiOjE3NTU2Nzg4NDB9.YixWgWeZwOc3-MaBRfKyglZOb9fyNivUGa5h0fN0lCw