### GET / 
GET http://localhost:5003

### Register a user POST / AUTH / REGISTER
POST http://localhost:5003/auth/register  
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1"
}

### Login a user POST / AUTH / LOGIN
POST http://localhost:5003/auth/login 
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Login a user POST / AUTH / LOGIN
POST http://localhost:5003/auth/login 
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1"
}


###
GET http://localhost:5003/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA


### 
POST http://localhost:5003/admin/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwMzYxMDMsImV4cCI6MTc1NjAzOTcwM30.wzHbjH-dwAJrKEx8Tmzm7EwXkBTr3n3AOIeamOQmnx8

{
  "name":"Smurfs",
  "category":["Animation", "Family", "Fantasy"],
  "language":"Tieng Viet",
  "duration":"120",
  "releaseDay":"2025-08-18",
  "IMDBrating":"9.1",
  "description":"Ke ve cuoc doi cua Ngo Long",
  "directors":["Trần Quốc Thiện"],
  "writers":["Trần Quốc Thiện"],
  "actors":["Ngô Bảo Long"],
  "ageLimit":"18",
  "posterURL":"posterURL",
  "backdropURL":"posterURL",
  "trailerURL": "trailerURL"
}


### 
PUT http://localhost:5003/admin/movies/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA
{
  "name":"f1",
  "category":["Tinh cam", "Kinh di"],
  "language":"Tieng Viet",
  "duration":"120",
  "releaseDay":"2025-08-18",
  "IMDBrating":"9.1",
  "description":"Ke ve cuoc doi cua Ngo Long",
  "directors":["Trần Quốc Thiện"],
  "writers":["Trần Quốc Thiện"],
  "actors":["Ngô Bảo Long"],
  "ageLimit":"18",
  "posterURL":"posterURL",
  "backdropURL":"posterURL"
}
###
GET http://localhost:5003/admin/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwMTk3MjIsImV4cCI6MTc1NjAyMzMyMn0._COv0uhtEkH4MPrShvk5Sp8CcKLnBW2XJLfyKxE7xp8

###
DELETE http://localhost:5003/admin/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NjgxOTYsImV4cCI6MTc1NTY3MTc5Nn0.tqGj6qOXp2g7yyes1KDs1l--5yAwYow2NLLO7jKhoSA

### 
GET http://localhost:5003/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2ODA0NzcsImV4cCI6MTc1NTY4NDA3N30.oKP-CzGsRUCm5AJIKJFVM6KkVh2S2eW8f2xI5gfXLcU

###
POST http://localhost:5003/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzMzNDAsImV4cCI6MTc1NTY3Njk0MH0.8Dfs_RmGNimo5mX0hOgiQsg8yryN8g7nUnFD7GmglLE

{
  "email": "thinh@gmail.com",
  "password": "123456",
  "role": "user"
}


###
PUT http://localhost:5003/admin/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzY5NjgsImV4cCI6MTc1NTY4MDU2OH0.hNPxaZC9fawjRAWOjjj3wissFSVw6gqTeVchZSZFUo4

{
  "role": "user"
}

### 
DELETE http://localhost:5003/admin/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU2NzMzNDAsImV4cCI6MTc1NTY3Njk0MH0.8Dfs_RmGNimo5mX0hOgiQsg8yryN8g7nUnFD7GmglLE













------------ ------------------------------------------------------------

                                                                  CINEMA  


###
POST http://localhost:5003/admin/cinemas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4MDIxMjksImV4cCI6MTc1NTgwNTcyOX0.5rYPFUQd-F6H5YcrF0_oG7ZeS2TOhL9ph_vLBHRvpXE

{
  "cinemaName": "CGV Long Xuyen",
  "address": "123 Ly Thai To, Phuong Long Xuyen, An Giang",
  "city": "An Giang",
  "phone": "0901234555"
}

###
GET http://localhost:5003/admin/cinemas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4MDIxMjksImV4cCI6MTc1NTgwNTcyOX0.5rYPFUQd-F6H5YcrF0_oG7ZeS2TOhL9ph_vLBHRvpXE


###   
GET http://localhost:5003/admin/cinemas/2
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4MDIxMjksImV4cCI6MTc1NTgwNTcyOX0.5rYPFUQd-F6H5YcrF0_oG7ZeS2TOhL9ph_vLBHRvpXE

### 
PUT http://localhost:5003/admin/cinemas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4MDIxMjksImV4cCI6MTc1NTgwNTcyOX0.5rYPFUQd-F6H5YcrF0_oG7ZeS2TOhL9ph_vLBHRvpXE

{
  "cinemaName": "CGV Vincom Dong Khoi",
  "address": "123 Dong Khoi, Quan 1, HCM",
  "city": "Ho Chi Minh City",
  "phone": "0901234555"
}

### 
DELETE http://localhost:5003/admin/cinemas/1
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4MDIxMjksImV4cCI6MTc1NTgwNTcyOX0.5rYPFUQd-F6H5YcrF0_oG7ZeS2TOhL9ph_vLBHRvpXE





------------ --------------------------------------------------------- LAYOUT 
### POST / ADMIN / LAYOUTS 
POST http://localhost:5003/admin/layouts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNTQ2OTEsImV4cCI6MTc1NjA1ODI5MX0.kAGh0zJw2RO1G7jVXpY4w6MnaLLzzB7AeeFL6d-s4-M

{
  "numRow":5,
  "numCol":5,
  "seats":
  [
    [
      {"rowNum":0,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":0,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":0,"colNum":2,"seatID":null,"type":"regular","price":12},
      {"rowNum":0,"colNum":3,"seatID":null,"type":"regular","price":12},
      {"rowNum":0,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":1,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":2,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":2,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":2,"seatID":null,"type":"regular","price":12},
      {"rowNum":2,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":4,"seatID":null,"type":"path","price":0}
      ],
    [
      {"rowNum":3,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":3,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":3,"colNum":2,"seatID":null,"type":"coupleLeft","price":12},
      {"rowNum":3,"colNum":3,"seatID":null,"type":"coupleRight","price":12},
      {"rowNum":3,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":4,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":2,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":4,"seatID":null,"type":"path","price":0}
    ]
  ]
}

### 
GET http://localhost:5003/admin/layouts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwMjczMDcsImV4cCI6MTc1NjAzMDkwN30.Iyb1_H-LFsKqA9RrJFHfj5LiZwNXnKvqKKi7f6cjLKU

### 
GET http://localhost:5003/admin/layouts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwMjE2NDIsImV4cCI6MTc1NjAyNTI0Mn0.MeOM6XxM1UbT3IhEWz9V_LjO2Z4LdQ7e74OHm84rXAE

###
GET http://localhost:5003/admin/layouts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNDg2ODQsImV4cCI6MTc1NjA1MjI4NH0.x__YI5gtgArg8mKZTMvL3IJLOOYQNXtxc-i4EhHN1t4


###
GET http://localhost:5003/admin/layouts/room/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNTMwMjgsImV4cCI6MTc1NjA1NjYyOH0.iM3HfX_kiYSKejTTh7G9jUYw4wrEkgeRpuv7wr8DM1Q


### 
DELETE http://localhost:5003/admin/layouts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwMjE2NDIsImV4cCI6MTc1NjAyNTI0Mn0.MeOM6XxM1UbT3IhEWz9V_LjO2Z4LdQ7e74OHm84rXAE

###
PUT http://localhost:5003/admin/layouts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNTQwNjEsImV4cCI6MTc1NjA1NzY2MX0.N3XfzSR6w0t1uTwkJerZzcwKpbLsRJqemgMpkaQEn9M

{
  "numRow":5,
  "numCol":5,
  "seats":
  [
    [
      {"rowNum":0,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":0,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":0,"colNum":2,"seatID":null,"type":"regular","price":12},
      {"rowNum":0,"colNum":3,"seatID":null,"type":"regular","price":12},
      {"rowNum":0,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":1,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":2,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":1,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":2,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":2,"seatID":null,"type":"regular","price":12},
      {"rowNum":2,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":2,"colNum":4,"seatID":null,"type":"path","price":0}
      ],
    [
      {"rowNum":3,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":3,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":3,"colNum":2,"seatID":null,"type":"coupleLeft","price":12},
      {"rowNum":3,"colNum":3,"seatID":null,"type":"coupleRight","price":12},
      {"rowNum":3,"colNum":4,"seatID":null,"type":"path","price":0}
    ],
    [
      {"rowNum":4,"colNum":0,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":1,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":2,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":3,"seatID":null,"type":"path","price":0},
      {"rowNum":4,"colNum":4,"seatID":null,"type":"path","price":0}
    ]
  ]
}

###
----------------------------------------- ROOM 
### 
POST http://localhost:5003/admin/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNDg2ODQsImV4cCI6MTc1NjA1MjI4NH0.x__YI5gtgArg8mKZTMvL3IJLOOYQNXtxc-i4EhHN1t4

{
  "cinemaID": 3,
  "roomName": "P05",
  "capacity": 70,
  "layoutID": 2
}

### 
GET http://localhost:5003/admin/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNDg2ODQsImV4cCI6MTc1NjA1MjI4NH0.x__YI5gtgArg8mKZTMvL3IJLOOYQNXtxc-i4EhHN1t4

###
GET http://localhost:5003/admin/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNjM1MjQsImV4cCI6MTc1NjA2NzEyNH0.rsthNLn1f7amMrrym6HDNXcJ54HE4chCwnFwjgh8nDg


###
DELETE http://localhost:5003/admin/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNDg2ODQsImV4cCI6MTc1NjA1MjI4NH0.x__YI5gtgArg8mKZTMvL3IJLOOYQNXtxc-i4EhHN1t4


###
PUT http://localhost:5003/admin/rooms/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNDg2ODQsImV4cCI6MTc1NjA1MjI4NH0.x__YI5gtgArg8mKZTMvL3IJLOOYQNXtxc-i4EhHN1t4

{
  "cinemaID": 2,
  "roomName": "PC02",
  "capacity": 80,
  "layoutID": 7
}




###
---------------------------------------------------------------- SHOWTIME
###



POST http://localhost:5003/admin/showtimes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNjExNDMsImV4cCI6MTc1NjA2NDc0M30.Q6FTBaDlCisGY_Tcr3DdDF3cBuNyCncsubE0PVfPrTU

{
  "movieID": 2,
  "roomID": 3,
  "cinemaID": 3,
  "showDate": "2025-08-21",
  "startTime": "19:30:00",
  "endTime": "22:00:00"
}


### 
GET http://localhost:5003/admin/showtimes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNTY3NDUsImV4cCI6MTc1NjA2MDM0NX0.5osRf-VdO1OAEpyGDCDzA0AMDUcNivqGToxJaNEbpk4

### 
GET http://localhost:5003/admin/showtimes/room/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNjExNDMsImV4cCI6MTc1NjA2NDc0M30.Q6FTBaDlCisGY_Tcr3DdDF3cBuNyCncsubE0PVfPrTU

### 
DELETE http://localhost:5003/admin/showtimes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNjExNDMsImV4cCI6MTc1NjA2NDc0M30.Q6FTBaDlCisGY_Tcr3DdDF3cBuNyCncsubE0PVfPrTU

### 
PUT http://localhost:5003/admin/showtimes/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYwNjExNDMsImV4cCI6MTc1NjA2NDc0M30.Q6FTBaDlCisGY_Tcr3DdDF3cBuNyCncsubE0PVfPrTU

{
  "movieID": 2,
  "roomID": 2,
  "cinemaID": 3,
  "showDate": "2025-12-04",
  "startTime": "19:30:00",
  "endTime": "22:00:00"
}


###

                                                                  USER
###


--------------------------------------------------------------- MOVIE

###
GET http://localhost:5003/user/movies
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4NTkwMDQsImV4cCI6MTc1NTg2MjYwNH0.74Lhlt0gcJ80H5-l62_nInVf40Om1-nWH_VoiyRtHu0


###
GET http://localhost:5003/user/movies/1?city=Ho Chi Minh City
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU4NTkwMDQsImV4cCI6MTc1NTg2MjYwNH0.74Lhlt0gcJ80H5-l62_nInVf40Om1-nWH_VoiyRtHu0

###
GET http://localhost:5003/user/movies/search?name=SHINCHAN
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTU5NTUwMTEsImV4cCI6MTc1NTk1ODYxMX0.O34gXSO3qcuoO7j0VlgjYiZWe5CuPtEHkzqR4YuSxEU
###
----------------------------------------------------- PROFILE

### 
GET http://localhost:5003/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU1NjgwNjcyLCJleHAiOjE3NTU2ODQyNzJ9.6Dwv4fUxXCzZ1lzZ7ZeJUArR7CHwf4CuK2EsTE_ejzE

### 
PUT http://localhost:5003/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU2MDY0NDA3LCJleHAiOjE3NTYwNjgwMDd9.mC7BiqpwkxMx-1stGApe9CKpeGYPyaIlIw0lFrJuYcQ

{
  "email": "thinh@gmail.com",
  "fullname": "Thinh Ngu Nhu Cho",
  "phone": "0913288527",
  "birthday": "2000-01-01",
  "favoriteCinema": 4
}

###
PUT http://localhost:5003/user/favoriteCinema
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYwNjYxOTEsImV4cCI6MTc1NjA2OTc5MX0.P5MaFqBsbJLo3mcZGakRV-NZDD4NTKrQlGPogIKDdw4

{
  "favoriteCinema": 4
}




###
-----------------------------------------------SHOWTIME
###
GET http://localhost:5003/user/showtimes?movieID=1&cinemaID=4&showDate=2025-08-23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYwOTA4MDgsImV4cCI6MTc1NjA5NDQwOH0.k7vQmK1Y_inMXcg2-ZKsp6v5ZRfefYQ38h0MNvFTR_4


